# Odometry model:
odom_model_type: diff
odom_alpha1    : 0.2 #0.4
odom_alpha2    : 0.2 #0.4
odom_alpha3    : 0.2 #0.5
odom_alpha4    : 0.2
#odom_alpha5    : 0.1

# Particle filter:
min_particles    : 1000  # 500
max_particles    : 5000
kld_err          : 0.05
kld_z            : 0.99
update_min_d     : 0.15   # 0.2
update_min_a     : 0.6  # 0.5
resample_interval: 4    # 2

# Measurement (laser) model:
laser_model_type         : likelihood_field
laser_max_beams          : 100
laser_z_hit              : 0.5
laser_z_short            : 0.05
laser_z_max              : 0.05
laser_z_rand             : 0.5
laser_sigma_hit          : 0.2
laser_lambda_short       : 0.1
laser_lambda_short       : 0.1
laser_likelihood_max_dist: 2.0

     
#initial pose

initial_pose_x : 0.692 #7.574 #0.692
initial_pose_y : 2.131 #4.465 #2.131
initial_pose_a : 0.782 #0.801 #0.782
initial_cov_aa : 0.05  #0.06
initial_cov_yy : 0.05   #0.25
initial_cov_xx : 0.05   #0.25

# Update/Rate params:
transform_tolerance: 0.2
gui_publish_rate   : 10.0

# Recovery:
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# Frames:
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

receive_map_topic: true
use_map_topic: map
