obstacle_range: 1.5
raytrace_range: 2.0
footprint: [[-0.205, -0.20], [-0.205, 0.20], [0.205, 0.20], [0.205, -0.20]]

# robot_radius: 0.25
# inflation_radius: 0.15

map_type: costmap
transform_tolerance: 2 # seconds
track_unknown_space: false

observation_sources: scan



scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: false, clearing: true, inf_is_valid: false, observation_persistence: 0.0, raytrace_range: 2.0, obstacle_range: 1.5}

# observation_sources: laser_scan_sensor 

# laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
